import { Project } from "@/types/blog";

const projectData: Project[] = [
  {
    id: 1,
    title: "n8n workflows",
    paragraph: "Different agent projects including an AI insurance estimation agent, and a loan demand analyzer.",
    image: "/images/projects/n8n.svg",
    tags: ["Automation", "AI", "Workflows"],
    publishDate: "2024-01-01",
    link: "https://example.com/n8n",
    width: 110,
    height: 30,
  },
  {
    id: 2,
    title: "AI Stock prediction",
    paragraph: "An AI stock prediction platform that uses LLaMa to analyze stock market trends.",
    image: "/images/projects/vestr.svg",
    tags: ["AI", "Stocks"],
    publishDate: "2024-01-01",
    link: "https://example.com/vestr",
    width: 140,
    height: 30,
  },
  {
    id: 3,
    title: "Data generation (Delib)",
    paragraph: "A data generation platform for Delib, focusing on creating vast databases.",
    image: "/images/projects/delib.svg",
    tags: ["Data", "Generation", "Clean"],
    publishDate: "2024-01-01",
    link: "https://example.com/delib",
    width: 26,
    height: 30,
  },
  {
    id: 4,
    title: "T-mobile partner (Fliggs)",
    paragraph: "An american mobile operator platform partnered with the giant T-Mobile",
    image: "/images/projects/tm.png",
    tags: ["Mobile", "Operator"],
    publishDate: "2024-01-01",
    link: "https://example.com/tmobile",
    width: 27,
    height: 30,
  },
  {
    id: 5,
    title: "AI Sizing (Weefizz)",
    paragraph: "An AI-powered sizing platform that helps users find the perfect fit for clothing.",
    image: "/images/projects/weefizz2.svg",
    tags: ["AI", "Sizing"],
    publishDate: "2024-01-01",
    link: "https://example.com/weefizz",
    width: 30,
    height: 30,
  },
  {
    id: 6,
    title: "Blockchain platforms",
    paragraph: "Numerous blockchain platforms for crypto, NFTs, and more.",
    image: "/images/projects/eth3.svg",
    tags: ["Ethereum", "NFT", "Crypto"],
    publishDate: "2024-01-01",
    link: "https://example.com/ethereum",
    width: 22,
    height: 30,
  },
];

export default projectData;
